### ISSUE TITLE
Some PMD parameters not working

### ISSUE THREAD

**Issue by cfbermudez** [sfdx-actions/pmd#13]
I'm not completely sure if this is an issue or if I am doing something wrong here.

I'm using this code:

```
# Setup pmd
- name: 'Setup PMD'
    uses: sfdx-actions/setup-pmd@v1

# Checkout the code
- name: 'Checkout source code'
    uses: actions/checkout@v2

# Run PMD Analysis
- name: 'Run PMD'
    run: |
        pmd -d ./force-app/main/default/ -R ./config/pmd-ruleset.xml -failOnViolation false -f html -shortnames -P linkPrefix="/some/path/" -P linePrefix="L" -reportfile ./ReportPMD.html

# Upload PMD report as an artifact
- name: 'Upload PMD report'
    uses: actions/upload-artifact@v3
    with:
    name: PMD-Apex-Report
    path: ./ReportPMD.html
```

It works just fine, I got the report in the GitHub action artifacts section.

But the HTML report is not considering the **-shortnames -P linkPrefix="/some/path/" -P linePrefix="L"** parameters.

The report looks like this:
![image](https://user-images.githubusercontent.com/10869565/167217072-a0438449-7574-4505-851f-0f6edc2dfcdc.png)

The report shows an entire path for the File Column ignoring the **-shortnames** parameter.
The File Colmun also should be a link to "/some/path/", specified in **-P linkPrefix="/some/path/"**
The Line Number should be an **L#**, specified in **-P linePrefix="L"**

Am I missing something?

Thanks!

PD, Is it possible to update or define the PMD version used? How Can I do that?
